# Generated by Django 6.0.3 on 2026-04-01 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id_city', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'OrderStatuses',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('id_parent_category', models.ForeignKey(blank=True, db_column='id_parent_category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category')),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id_address', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=10)),
                ('apartment_number', models.CharField(blank=True, max_length=10, null=True)),
                ('id_city', models.ForeignKey(db_column='id_city', on_delete=django.db.models.deletion.CASCADE, to='shop.city')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='shop.user')),
            ],
            options={
                'db_table': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.PositiveIntegerField(default=1)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('id_category', models.ForeignKey(db_column='id_category', on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('id_product', models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='shop.user')),
            ],
            options={
                'db_table': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('total_cost', models.PositiveIntegerField(default=0)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('id_address', models.ForeignKey(db_column='id_address', on_delete=django.db.models.deletion.CASCADE, to='shop.address')),
                ('id_status', models.ForeignKey(db_column='id_status', on_delete=django.db.models.deletion.CASCADE, to='shop.orderstatus')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='shop.user')),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id_cart', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('id_product', models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='shop.user')),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
    ]
